### ISSUE TITLE
sprout-git Cookbook Deprecations

### ISSUE THREAD

**Issue by trinitronx** [LyraPhase/sprout-wrap#197]
Need to replace / update many sprout cookbooks including `sprout-git`:

After `soloist` run Chef Client `13.10.0` on macOS Big Sur `11.6.2`
```
Deprecated features used!
  rename scope to new_resource.scope at 1 location:
    - /var/chef/cache/cookbooks/sprout-git/resources/config.rb:11:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
  rename setting_key to new_resource.setting_key at 1 location:
    - /var/chef/cache/cookbooks/sprout-git/resources/config.rb:11:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
  rename setting_value to new_resource.setting_value at 1 location:
    - /var/chef/cache/cookbooks/sprout-git/resources/config.rb:11:in `block in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
  rename setting_owner to new_resource.setting_owner at 1 location:
    - /var/chef/cache/cookbooks/sprout-git/resources/config.rb:12:in `block (2 levels) in class_from_file'
   See https://docs.chef.io/deprecations_namespace_collisions.html for further details.
```

**Comment by trinitronx** [comment]
Replacing `sprout-git` with [dotfiles repo][1] installed by `chezmoi`

[1]: https://github.com/trinitronx/dotfiles
[2]: https://www.chezmoi.io/
